<script setup lang="ts">
import { computed } from 'vue'

export interface IconProps {
  name: string
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl'
  color?: 'default' | 'cyan' | 'magenta' | 'orange' | 'purple' | 'green' | 'red' | 'yellow'
  variant?: 'solid' | 'outline' | 'duotone'
  spin?: boolean
  pulse?: boolean
}

const props = withDefaults(defineProps<IconProps>(), {
  size: 'md',
  color: 'default',
  variant: 'solid',
  spin: false,
  pulse: false
})

const sizeClasses = computed(() => {
  const sizes = {
    xs: 'w-3 h-3 text-xs',
    sm: 'w-4 h-4 text-sm',
    md: 'w-5 h-5 text-base',
    lg: 'w-6 h-6 text-lg',
    xl: 'w-8 h-8 text-xl',
    '2xl': 'w-10 h-10 text-2xl'
  }
  return sizes[props.size]
})

const colorClasses = computed(() => {
  const colors = {
    default: 'text-i3-text',
    cyan: 'text-i3-cyan',
    magenta: 'text-i3-magenta',
    orange: 'text-i3-orange',
    purple: 'text-i3-purple',
    green: 'text-i3-green',
    red: 'text-i3-red',
    yellow: 'text-i3-yellow'
  }
  return colors[props.color]
})

const animationClasses = computed(() => {
  const classes = []
  if (props.spin) classes.push('animate-spin')
  if (props.pulse) classes.push('animate-pulse')
  return classes.join(' ')
})

const iconMap: Record<string, string> = {
  // Navigation & UI
  'dashboard': '📊',
  'traffic': '📡',
  'websocket': '🔌',
  'repeater': '🔁',
  'intruder': '⚔️',
  'scanner': '🔍',
  'decoder': '🧩',
  'comparer': '⚖️',
  'plugins': '🔌',
  'settings': '⚙️',
  'export': '📄',
  'home': '🏠',
  'menu': '☰',
  'close': '✕',
  'search': '🔎',
  'filter': '🔽',
  'sort': '↕️',
  'refresh': '🔄',
  'download': '⬇️',
  'upload': '⬆️',
  'save': '💾',
  'delete': '🗑️',
  'edit': '✏️',
  'copy': '📋',
  'paste': '📝',
  'cut': '✂️',
  'undo': '↩️',
  'redo': '↪️',
  'play': '▶',
  'pause': '⏸️',
  'stop': '⏹️',
  'forward': '⏩',
  'backward': '⏪',
  'skip': '⏭️',
  'eject': '⏏️',

  // HTTP Methods
  'get': '📥',
  'post': '📤',
  'put': '📝',
  'delete': '🗑️',
  'patch': '🩹',
  'head': '🗣️',
  'options': '⚙️',
  'connect': '🔗',
  'trace': '👣',

  // Status & Feedback
  'success': '✅',
  'error': '❌',
  'warning': '⚠️',
  'info': 'ℹ️',
  'question': '❓',
  'help': '❓',
  'loading': '⏳',
  'spinner': '⟳',
  'check': '✔',
  'cross': '✖',
  'plus': '➕',
  'minus': '➖',
  'star': '⭐',
  'heart': '❤️',
  'bookmark': '🔖',
  'flag': '🚩',
  'pin': '📌',
  'tag': '🏷️',
  'label': '🏷️',

  // Security
  'lock': '🔒',
  'unlock': '🔓',
  'shield': '🛡️',
  'key': '🔑',
  'certificate': '📜',
  'security': '🔐',
  'vulnerability': '⚠️',
  'bug': '🐛',
  'exploit': '💣',
  'payload': '📦',
  'attack': '⚔️',
  'defense': '🛡️',

  // Network
  'network': '🌐',
  'server': '🖥️',
  'client': '💻',
  'proxy': '🔄',
  'firewall': '🔥',
  'router': '🔀',
  'switch': '🔌',
  'cloud': '☁️',
  'database': '🗄️',
  'storage': '💾',

  // Files & Documents
  'file': '📄',
  'folder': '📁',
  'folder-open': '📂',
  'document': '📄',
  'image': '🖼️',
  'video': '🎬',
  'audio': '🎵',
  'archive': '📦',
  'code': '💻',
  'json': '📋',
  'xml': '📄',
  'html': '🌐',
  'css': '🎨',
  'js': '📜',

  // Tools & Actions
  'hammer': '🔨',
  'wrench': '🔧',
  'screwdriver': '🪛',
  'tool': '🛠️',
  'terminal': '💻',
  'console': '⌨️',
  'command': '⌨️',
  'keyboard': '⌨️',
  'mouse': '🖱️',
  'cursor': '👆',
  'pointer': '👆',
  'hand': '🖐️',
  'grab': '✊',

  // Time & Date
  'clock': '🕐',
  'calendar': '📅',
  'timer': '⏱️',
  'stopwatch': '⏱️',
  'alarm': '⏰',
  'hourglass': '⏳',

  // Communication
  'mail': '📧',
  'message': '💬',
  'chat': '💭',
  'notification': '🔔',
  'bell': '🔔',
  'megaphone': '📣',
  'broadcast': '📢',

  // Charts & Data
  'chart-line': '📈',
  'chart-bar': '📊',
  'chart-pie': '🥧',
  'chart-area': '📈',
  'graph': '📈',
  'analytics': '📊',
  'statistics': '📊',
  'trend-up': '📈',
  'trend-down': '📉',
  'trend-stable': '➡️',

  // Arrows & Navigation
  'arrow-up': '↑',
  'arrow-down': '↓',
  'arrow-left': '←',
  'arrow-right': '→',
  'arrow-up-left': '↖️',
  'arrow-up-right': '↗️',
  'arrow-down-left': '↙️',
  'arrow-down-right': '↘️',
  'chevron-up': '▲',
  'chevron-down': '▼',
  'chevron-left': '◀',
  'chevron-right': '▶',
  'expand': '⤢',
  'collapse': '⤡',
  'fullscreen': '⛶',
  'minimize': '⤡',
  'maximize': '⤢',

  // Media
  'volume-up': '🔊',
  'volume-down': '🔉',
  'volume-mute': '🔇',
  'volume': '🔈',
  'music': '🎵',
  'sound': '🔊',
  'microphone': '🎤',
  'camera': '📷',
  'video-camera': '📹',
  'image': '🖼️',
  'gallery': '🖼️',

  // Misc
  'sun': '☀️',
  'moon': '🌙',
  'star': '⭐',
  'heart': '❤️',
  'thumbs-up': '👍',
  'thumbs-down': '👎',
  'smile': '😊',
  'frown': '😟',
  'neutral': '😐',
  'confused': '😕',
  'angry': '😠',
  'sad': '😢',
  'laugh': '😂',
  'cool': '😎',
  'wink': '😉',
  'surprised': '😮',
  'sick': '🤢',
  'dead': '😵',
  'alien': '👽',
  'robot': '🤖',
  'ghost': '👻',
  'skull': '💀',
  'poop': '💩',
  'fire': '🔥',
  'bomb': '💣',
  'lightning': '⚡',
  'sparkle': '✨',
  'magic': '✨',
  'rainbow': '🌈',
  'cloud': '☁️',
  'rain': '🌧️',
  'snow': '❄️',
  'wind': '💨',
  'tornado': '🌪️',
  'wave': '🌊',
  'droplet': '💧',
  'leaf': '🍃',
  'tree': '🌳',
  'flower': '🌸',
  'mountain': '⛰️',
  'beach': '🏖️',
  'desert': '🏜️',
  'island': '🏝️',
  'city': '🏙️',
  'building': '🏢',
  'house': '🏠',
  'castle': '🏰',
  'tent': '⛺',
  'rocket': '🚀',
  'airplane': '✈️',
  'car': '🚗',
  'bus': '🚌',
  'train': '🚂',
  'subway': '🚇',
  'bicycle': '🚲',
  'motorcycle': '🏍️',
  'boat': '🚤',
  'ship': '🚢',
  'truck': '🚚',
  'ambulance': '🚑',
  'police': '🚔',
  'fire-truck': '🚒',
  'taxi': '🚕',
  'helicopter': '🚁',

  // Tech & Development
  'code': '💻',
  'terminal': '⌨️',
  'bug': '🐛',
  'debug': '🐛',
  'test': '🧪',
  'deploy': '🚀',
  'build': '🔨',
  'git': '📦',
  'branch': '🌿',
  'merge': '🔀',
  'pull-request': '📥',
  'commit': '💾',
  'push': '📤',
  'clone': '📋',
  'fork': '🍴',
  'star': '⭐',
  'watch': '👁️',
  'issue': '🐛',
  'milestone': '🚩',
  'release': '🎉',
  'tag': '🏷️',
  'label': '🏷️',
  'project': '📁',
  'workspace': '📂',
  'package': '📦',
  'dependency': '🔗',
  'node': '⬤',
  'component': '🧩',
  'module': '📦',
  'library': '📚',
  'framework': '🏗️',
  'api': '🔌',
  'endpoint': '📍',
  'route': '🛣️',
  'middleware': '🔀',
  'service': '⚙️',
  'worker': '👷',
  'queue': '📋',
  'cache': '💾',
  'database': '🗄️',
  'storage': '💾',
  'backup': '💾',
  'restore': '🔄',
  'sync': '🔄',
  'cloud': '☁️',
  'server': '🖥️',
  'client': '💻',
  'mobile': '📱',
  'tablet': '📲',
  'desktop': '🖥️',
  'laptop': '💻',
  'monitor': '🖥️',
  'keyboard': '⌨️',
  'mouse': '🖱️',
  'printer': '🖨️',
  'scanner': '🔍',
  'camera': '📷',
  'microphone': '🎤',
  'speaker': '🔊',
  'headphones': '🎧',
  'watch': '⌚',
  'glasses': '👓',
  'sunglasses': '🕶️',

  // Programming Languages
  'javascript': '📜',
  'typescript': '📘',
  'python': '🐍',
  'rust': '🦀',
  'go': '🐹',
  'java': '☕',
  'c': '©️',
  'cpp': '©️',
  'csharp': '©️',
  'php': '🐘',
  'ruby': '💎',
  'swift': '🦉',
  'kotlin': '🤖',
  'dart': '🎯',
  'sql': '🗄️',
  'html': '🌐',
  'css': '🎨',
  'sass': '🎨',
  'less': '🎨',
  'json': '📋',
  'xml': '📄',
  'yaml': '📄',
  'markdown': '📝',

  // Tools & Editors
  'vscode': '💻',
  'vim': '⌨️',
  'emacs': '⌨️',
  'sublime': '⌨️',
  'atom': '⚛️',
  'webstorm': '💻',
  'intellij': '💻',
  'eclipse': '💻',
  'xcode': '💻',
  'android-studio': '🤖',

  // Platforms & Services
  'github': '🐙',
  'gitlab': '🦊',
  'bitbucket': '🧢',
  'docker': '🐳',
  'kubernetes': '☸️',
  'aws': '☁️',
  'azure': '☁️',
  'gcp': '☁️',
  'heroku': '🟣',
  'vercel': '▲',
  'netlify': '🟢',
  'cloudflare': '🌐',

  // Security Tools
  'burp': '🔍',
  'wireshark': '🔍',
  'nmap': '🗺️',
  'metasploit': '💣',
  'sqlmap': '🗄️',
  'nikto': '🔍',
  'zap': '⚡',
  'owasp': '🛡️',

  // HTTP Status Codes
  'status-200': '✅',
  'status-201': '✅',
  'status-204': '✅',
  'status-301': '↪️',
  'status-302': '↪️',
  'status-304': '💾',
  'status-400': '⚠️',
  'status-401': '🔒',
  'status-403': '🚫',
  'status-404': '❓',
  'status-405': '⚠️',
  'status-409': '⚔️',
  'status-410': '👻',
  'status-429': '⏱️',
  'status-500': '💥',
  'status-502': '🔌',
  'status-503': '🚧',
  'status-504': '⏰',

  // Severity Levels
  'critical': '🔴',
  'high': '🟠',
  'medium': '🟡',
  'low': '🟢',
  'info': '🔵',
  'unknown': '⚪',

  // Common Actions
  'add': '➕',
  'remove': '➖',
  'clear': '🗑️',
  'reset': '🔄',
  'apply': '✅',
  'cancel': '❌',
  'confirm': '✅',
  'submit': '📤',
  'send': '📤',
  'receive': '📥',
  'share': '📤',
  'link': '🔗',
  'unlink': '🔗',
  'attach': '📎',
  'detach': '📎',
  'upload': '⬆️',
  'download': '⬇️',
  'import': '📥',
  'export': '📤',
  'print': '🖨️',
  'preview': '👁️',
  'view': '👁️',
  'edit': '✏️',
  'modify': '✏️',
  'update': '🔄',
  'upgrade': '⬆️',
  'downgrade': '⬇️',
  'install': '⬇️',
  'uninstall': '❌',
  'enable': '✅',
  'disable': '❌',
  'activate': '✅',
  'deactivate': '❌',
  'connect': '🔗',
  'disconnect': '🔌',
  'login': '🔑',
  'logout': '🚪',
  'signup': '📝',
  'register': '📝',
  'forgot': '❓',
  'reset-password': '🔑',
  'change-password': '🔑',
  'profile': '👤',
  'account': '👤',
  'user': '👤',
  'users': '👥',
  'team': '👥',
  'group': '👥',
  'organization': '🏢',
  'company': '🏢',
  'business': '🏢',

  // Project Management
  'project': '📁',
  'task': '📋',
  'tasks': '📋',
  'todo': '📝',
  'done': '✅',
  'in-progress': '⏳',
  'blocked': '🚫',
  'backlog': '📦',
  'sprint': '🏃',
  'milestone': '🚩',
  'epic': '📖',
  'story': '📖',
  'bug': '🐛',
  'feature': '✨',
  'improvement': '📈',
  'refactor': '🔨',
  'documentation': '📚',
  'testing': '🧪',
  'deployment': '🚀',
  'release': '🎉',
  'version': '🏷️',
  'changelog': '📋',
  'roadmap': '🗺️',

  // INT3RCEPTOR Specific
  'intercept': '🎯',
  'proxy': '🔄',
  'request': '📤',
  'response': '📥',
  'header': '📋',
  'body': '📄',
  'query': '❓',
  'param': '🔧',
  'cookie': '🍪',
  'session': '🎫',
  'token': '🎟️',
  'auth': '🔑',
  'certificate': '📜',
  'tls': '🔒',
  'ssl': '🔒',
  'http': '🌐',
  'https': '🔒',
  'http2': '⚡',
  'websocket': '🔌',
  'grpc': '🔌',
  'graphql': '🔷',
  'rest': '🌐',
  'api': '🔌',
  'endpoint': '📍',
  'route': '🛣️',
  'middleware': '🔀',
  'plugin': '🔌',
  'extension': '🔌',
  'addon': '🔌',
  'module': '📦',
  'component': '🧩',
  'widget': '🧩',
  'layout': '📐',
  'theme': '🎨',
  'style': '🎨',
  'design': '🎨',
  'mockup': '🖼️',
  'prototype': '🖼️',
  'wireframe': '📐',
  'screenshot': '📸',
  'video': '🎬',
  'animation': '🎬',
  'transition': '🔄',
  'effect': '✨',
  'filter': '🔽',
  'sort': '↕️',
  'group': '👥',
  'ungroup': '👤',
  'merge': '🔀',
  'split': '✂️',
  'join': '🔗',
  'separate': '✂️',
  'combine': '🔗',
  'extract': '📤',
  'transform': '🔄',
  'convert': '🔄',
  'encode': '🔐',
  'decode': '🔓',
  'encrypt': '🔐',
  'decrypt': '🔓',
  'hash': '🔐',
  'sign': '✍️',
  'verify': '✅',
  'validate': '✅',
  'check': '✅',
  'test': '🧪',
  'debug': '🐛',
  'profile': '📊',
  'monitor': '📊',
  'analyze': '📊',
  'audit': '🔍',
  'scan': '🔍',
  'inspect': '🔍',
  'examine': '🔍',
  'investigate': '🔍',
  'explore': '🔍',
  'discover': '🔍',
  'find': '🔍',
  'search': '🔎',
  'locate': '📍',
  'identify': '🏷️',
  'classify': '🏷️',
  'categorize': '🏷️',
  'organize': '📁',
  'arrange': '📁',
  'sort': '↕️',
  'order': '↕️',
  'rank': '🏆',
  'rate': '⭐',
  'score': '🎯',
  'measure': '📏',
  'calculate': '🧮',
  'compute': '🧮',
  'process': '⚙️',
  'execute': '▶',
  'run': '▶',
  'start': '▶',
  'stop': '⏹️',
  'pause': '⏸️',
  'resume': '▶',
  'continue': '▶',
  'abort': '⏹️',
  'terminate': '⏹️',
  'kill': '⏹️',
  'restart': '🔄',
  'reboot': '🔄',
  'shutdown': '⏹️',
  'power': '⏻',
  'battery': '🔋',
  'signal': '📶',
  'wifi': '📶',
  'bluetooth': '📶',
  'nfc': '📶',
  'usb': '🔌',
  'hdmi': '🔌',
  'audio': '🔊',
  'video': '📹',
  'display': '🖥️',
  'screen': '🖥️',
  'touch': '👆',
  'gesture': '👆',
  'voice': '🎤',
  'face': '👤',
  'fingerprint': '👆',
  'iris': '👁️',
  'biometric': '👆',

  // Default fallback
  'default': '❓'
}

const icon = computed(() => iconMap[props.name.toLowerCase()] || iconMap['default'])
</script>

<template>
  <span
    :class="[
      'inline-flex items-center justify-center',
      sizeClasses,
      colorClasses,
      animationClasses
    ]"
    :aria-hidden="true"
    role="img"
  >
    {{ icon }}
  </span>
</template>
